typography_spectrum: 0.5939305978827178
color:
  brandStrength: 0.3296970676165074
  lightness: 0.6954883069265634
  saturation: 0.6013504704460502
  rhythmicContrast: 0.5115815666504204
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.3407939770258963
author:
  name: Daniel Stiker
  email: dan@danielstiker.me
name: Life and Organization Coach
navigation:
  - name: Services
    id: b3ed6559-b69a-4bec-95b2-b16e8ca9812e
    type: content
title: Making life and work make sense
description: Making life and work make sense
