typography_spectrum: 0.9624768153298646
color:
  brandStrength: 0.3296970676165074
  lightness: 0.6954883069265634
  saturation: 0.6013504704460502
  rhythmicContrast: 0.5115815666504204
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.41796038183383644
author:
  name: Daniel Stiker
  email: dan@danielstiker.me
name: Life and Organization Coach
title: Making life and work make sense
description: '#worklifebalance'
